import 'package:flutter/material.dart';
import '../models/transaction.dart';
import '../models/budget_balances.dart';
import '../models/period_history.dart';
import '../services/database.dart';
import '../services/auth_service.dart';
import '../services/user_service.dart';
import '../services/api_service.dart';
import '../utils/date_utils.dart';
import '../widgets/calendar.dart';
import '../widgets/transaction_list.dart';
import '../widgets/add_transaction_dialog.dart';
import '../widgets/day_details_dialog.dart';
import '../widgets/period_selector_dialog.dart';
import '../widgets/period_history_dialog.dart';
import '../widgets/period_selection_dialog.dart';
import '../widgets/balance_chart.dart';
import '../theme/app_theme.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final DatabaseService _databaseService = DatabaseService();
  final AuthService _authService = AuthService();
  final UserService _userService = UserService();
  final ApiService _apiService = ApiService();

  String? _userName;
  bool _isLoadingUser = true;

  int _selectedYear = DateTime.now().year;
  DateTime _startDate = DateTime(DateTime.now().year, DateTime.now().month, 1);
  DateTime _endDate =
      DateTime(DateTime.now().year, DateTime.now().month + 1, 0);

  bool _showTransactions = false;
  List<Transaction> _transactions = [];
  bool _isLoading = true;
  List<PeriodHistory> _periodHistories = [];
  bool _periodSelected = false;
  final GlobalKey<CalendarWidgetState> _calendarKey =
      GlobalKey<CalendarWidgetState>();
  bool _isWeeklyView = false;

  @override
  void initState() {
    super.initState();
    // Assume current year but don't set dates yet
    _selectedYear = DateTime.now().year;
    // Prompt for period selection after first frame
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      await _loadUserData();
      await _loadPeriodHistories();
      await _selectDateRangeOnStartup();
    });
  }

  Future<void> _loadUserData() async {
    try {
      final user = await _userService.getCurrentUser();
      if (mounted) {
        setState(() {
          _userName = user?.name;
          _isLoadingUser = false;
        });
      }
    } catch (e) {
      print('Erro ao carregar dados do usuário: $e');
      if (mounted) {
        setState(() {
          _isLoadingUser = false;
        });
      }
    }
  }

  Future<void> _loadPeriodHistories() async {
    try {
      final periods = await _apiService.getAllPeriodHistories();
      if (mounted) {
        setState(() {
          _periodHistories = periods;
        });
      }
    } catch (e) {
      print('Erro ao carregar histórico de períodos: $e');
    }
  }

  Future<void> _selectDateRangeOnStartup() async {
    // Set default to current month
    final now = DateTime.now();
    _startDate = DateTime(now.year, now.month, 1);
    _endDate = DateTime(now.year, now.month + 1, 0);

    // Show period selection dialog if user has past periods
    if (_periodHistories.isNotEmpty) {
      final result = await showDialog(
        context: context,
        barrierDismissible: false,
        builder: (context) => PeriodSelectionDialog(
          pastPeriods: _periodHistories,
          currentYear: _selectedYear,
        ),
      );

      if (result != null && mounted) {
        if (result['type'] == 'existing') {
          final period = result['period'] as PeriodHistory;
          setState(() {
            _startDate = period.startDate;
            _endDate = period.endDate;
            _selectedYear = period.startDate.year;
            _periodSelected = true;
          });
          await _loadTransactions(savePeriod: false);
        } else if (result['type'] == 'new') {
          setState(() {
            _selectedYear = result['year'];
            _startDate = result['startDate'];
            _endDate = result['endDate'];
            _periodSelected = true;
          });
          await _loadTransactions(savePeriod: true);
        }
      }
    } else {
      // No past periods, show period selector
      await _selectPeriod();
    }
  }

  Future<void> _loadTransactions({bool savePeriod = false}) async {
    setState(() => _isLoading = true);
    final transactions = await _databaseService.getTransactionsInRange(
      _startDate,
      _endDate,
    );

    // Save period history with transaction IDs only if requested
    if (savePeriod) {
      final transactionIds = transactions.map((t) => t.id).toList();
      try {
        final periodHistory = PeriodHistory(
          id: '', // Will be generated by backend
          startDate: _startDate,
          endDate: _endDate,
          transactionIds: transactionIds,
        );
        await _apiService.savePeriodHistory(periodHistory);
        await _loadPeriodHistories();
      } catch (e) {
        print('Erro ao salvar histórico de período: $e');
      }
    }

    setState(() {
      _transactions = transactions;
      _isLoading = false;
    });
  }

  Future<void> _selectPeriod() async {
    final result = await showDialog(
      context: context,
      builder: (context) => PeriodSelectorDialog(
        selectedYear: _selectedYear,
        startDate: _startDate,
        endDate: _endDate,
      ),
    );

    if (result != null && mounted) {
      setState(() {
        _selectedYear = result['year'];
        _startDate = result['startDate'];
        _endDate = result['endDate'];
        _periodSelected = true;
      });
      await _loadTransactions(savePeriod: true);
    }
  }

  Future<void> _showPeriodHistory() async {
    await showDialog(
      context: context,
      builder: (context) => PeriodHistoryDialog(
        periods: _periodHistories,
        onPeriodSelected: (period) async {
          setState(() {
            _startDate = period.startDate;
            _endDate = period.endDate;
            _selectedYear = period.startDate.year;
          });
          await _loadTransactions(savePeriod: false);
        },
        onPeriodDeleted: (id) async {
          try {
            await _apiService.deletePeriodHistory(id);
            await _loadPeriodHistories();
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Período excluído com sucesso')),
              );
            }
          } catch (e) {
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(content: Text('Erro ao excluir período: $e')),
              );
            }
          }
        },
      ),
    );
  }

  Future<void> _showAddTransactionDialog() async {
    final result = await showDialog(
      context: context,
      builder: (context) => const AddTransactionDialog(),
    );

    if (result == true) {
      await _loadTransactions(savePeriod: false);
    }
  }

  Future<void> _showTransactionsAsPopup() async {
    await showDialog(
      context: context,
      builder: (context) => Dialog(
        child: Container(
          constraints: BoxConstraints(
            maxWidth: MediaQuery.of(context).size.width * 0.9,
            maxHeight: MediaQuery.of(context).size.height * 0.8,
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              // Cabeçalho do diálogo
              Container(
                padding: const EdgeInsets.all(16),
                decoration: const BoxDecoration(
                  color: AppTheme.white,
                  borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(24),
                    topRight: Radius.circular(24),
                  ),
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      'Transações',
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                            fontWeight: FontWeight.w600,
                          ),
                    ),
                    IconButton(
                      onPressed: () => Navigator.of(context).pop(),
                      icon: const Icon(Icons.close),
                    ),
                  ],
                ),
              ),
              // Lista de transações
              Expanded(
                child: TransactionListWidget(
                  transactions: _transactions,
                  onTransactionUpdated: () async {
                    await _loadTransactions(savePeriod: false);
                    if (mounted) {
                      Navigator.of(context).pop();
                      _showTransactionsAsPopup();
                    }
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> _showDayDetails(DateTime date) async {
    // Calcular saldo disponível para este dia
    final allTransactions = await _databaseService.getTransactionsInRange(
      _startDate,
      date,
    );

    double balance = 0.0;
    double gastos = 0.0;
    double lazer = 0.0;
    double poupanca = 0.0;

    for (var transaction in allTransactions) {
      final transactionDate = DateTime(
        transaction.date.year,
        transaction.date.month,
        transaction.date.day,
      );
      final checkDate = DateTime(date.year, date.month, date.day);

      if (transactionDate.isBefore(checkDate) ||
          transactionDate.isAtSameMomentAs(checkDate)) {
        if (transaction.type == TransactionType.ganho) {
          balance += transaction.amount;

          // Calcular valores do salário
          if (transaction.isSalary) {
            final values = transaction.salaryValues;
            if (values != null) {
              gastos += values.gastos;
              lazer += values.lazer;
              poupanca += values.poupanca;
            }
          }
        } else {
          balance -= transaction.amount;

          // Deduzir da categoria correspondente
          switch (transaction.expenseBudgetCategory) {
            case ExpenseBudgetCategory.gastos:
              gastos -= transaction.amount;
              break;
            case ExpenseBudgetCategory.lazer:
              lazer -= transaction.amount;
              break;
            case ExpenseBudgetCategory.poupanca:
              poupanca -= transaction.amount;
              break;
            case null:
              break;
          }
        }
      }
    }

    final dayTransactions = _transactions.where((t) {
      final transactionDate = DateTime(t.date.year, t.date.month, t.date.day);
      return isSameDay(transactionDate, date);
    }).toList();

    final budgetBalances = (gastos != 0 || lazer != 0 || poupanca != 0)
        ? BudgetBalances(gastos: gastos, lazer: lazer, poupanca: poupanca)
        : null;

    if (mounted) {
      showDialog(
        context: context,
        builder: (context) => DayDetailsDialog(
          date: date,
          transactions: dayTransactions,
          availableBalance: balance,
          budgetBalances: budgetBalances,
        ),
      );
    }
  }

  Map<String, double> _calculateSummary() {
    double totalGains = 0.0;
    double totalExpenses = 0.0;

    for (var transaction in _transactions) {
      if (transaction.type == TransactionType.ganho) {
        totalGains += transaction.amount;
      } else {
        totalExpenses += transaction.amount;
      }
    }

    return {
      'gains': totalGains,
      'expenses': totalExpenses,
    };
  }

  String _formatPeriodDates(DateTime startDate, DateTime endDate) {
    final startDay = startDate.day.toString().padLeft(2, '0');
    final startMonth = startDate.month.toString().padLeft(2, '0');
    final endDay = endDate.day.toString().padLeft(2, '0');
    final endMonth = endDate.month.toString().padLeft(2, '0');
    
    return '$startDay/$startMonth - $endDay/$endMonth';
  }

  Future<double> _calculateInitialBalance() async {
    // Calcular saldo de todas as transações antes do período começar
    try {
      final beforePeriod = _startDate.subtract(const Duration(days: 1));
      final allTransactions = await _databaseService.getTransactionsInRange(
        DateTime(1900, 1, 1), // Data muito antiga para pegar todas
        beforePeriod,
      );

      double balance = 0.0;
      for (var transaction in allTransactions) {
        if (transaction.type == TransactionType.ganho) {
          balance += transaction.amount;
        } else {
          balance -= transaction.amount;
        }
      }
      return balance;
    } catch (e) {
      print('Erro ao calcular saldo inicial: $e');
      return 0.0;
    }
  }

  Map<DateTime, double> _calculateDailyBalancesForChart() {
    final days = getDaysInRange(_startDate, _endDate);
    final Map<DateTime, double> dailyBalances = {};

    if (_transactions.isEmpty) {
      for (var day in days) {
        final dayOnly = DateTime(day.year, day.month, day.day);
        dailyBalances[dayOnly] = 0.0;
      }
      return dailyBalances;
    }

    // Ordenar transações por data
    final sortedTransactions = List<Transaction>.from(_transactions)
      ..sort((a, b) => a.date.compareTo(b.date));

    int transactionIndex = 0;

    for (var day in days) {
      final currentDay = DateTime.utc(day.year, day.month, day.day);
      double dayBalance = 0.0;

      // Processar todas as transações deste dia
      while (transactionIndex < sortedTransactions.length) {
        final transaction = sortedTransactions[transactionIndex];
        final transactionDate = DateTime.utc(
          transaction.date.year,
          transaction.date.month,
          transaction.date.day,
        );

        if (transactionDate.isAfter(currentDay)) {
          break;
        }

        if (transactionDate.year == currentDay.year &&
            transactionDate.month == currentDay.month &&
            transactionDate.day == currentDay.day) {
          if (transaction.type == TransactionType.ganho) {
            dayBalance += transaction.amount;
          } else {
            dayBalance -= transaction.amount;
          }
          transactionIndex++;
        } else {
          break;
        }
      }

      final dayOnly = DateTime(day.year, day.month, day.day);
      dailyBalances[dayOnly] = dayBalance;
    }

    return dailyBalances;
  }

  @override
  Widget build(BuildContext context) {
    final summary = _calculateSummary();

    return Scaffold(
      backgroundColor: AppTheme.white,
      body: SafeArea(
        child: Column(
          children: [
            // Cabeçalho
            Container(
              padding: const EdgeInsets.all(12),
              decoration: const BoxDecoration(
                color: AppTheme.white,
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'FinCal',
                    style: Theme.of(context).textTheme.displayMedium,
                  ),
                  PopupMenuButton<String>(
                    icon: const Icon(Icons.account_circle),
                    onSelected: (value) async {
                      if (value == 'logout') {
                        // Mostrar diálogo de confirmação
                        final shouldLogout = await showDialog<bool>(
                          context: context,
                          builder: (context) => AlertDialog(
                            title: const Text('Confirmar Logout'),
                            content: const Text('Tem certeza que deseja sair?'),
                            actions: [
                              TextButton(
                                onPressed: () =>
                                    Navigator.of(context).pop(false),
                                child: const Text('Cancelar'),
                              ),
                              ElevatedButton(
                                onPressed: () =>
                                    Navigator.of(context).pop(true),
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: AppTheme.expenseRed,
                                ),
                                child: const Text('Sair'),
                              ),
                            ],
                          ),
                        );

                        if (shouldLogout == true && mounted) {
                          await _authService.signOut();
                        }
                      }
                    },
                    itemBuilder: (context) => [
                      // Informações do usuário
                      PopupMenuItem(
                        enabled: false,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            if (_isLoadingUser)
                              const SizedBox(
                                width: 16,
                                height: 16,
                                child:
                                    CircularProgressIndicator(strokeWidth: 2),
                              )
                            else
                              Text(
                                _userName ??
                                    _authService.currentUser?.email ??
                                    'Usuário',
                                style: Theme.of(context)
                                    .textTheme
                                    .bodyMedium
                                    ?.copyWith(
                                      fontWeight: FontWeight.w600,
                                    ),
                              ),
                            if (_userName != null &&
                                _authService.currentUser?.email != null) ...[
                              const SizedBox(height: 4),
                              Text(
                                _authService.currentUser!.email!,
                                style: Theme.of(context)
                                    .textTheme
                                    .bodySmall
                                    ?.copyWith(
                                      color: AppTheme.darkGray,
                                    ),
                              ),
                            ],
                            const SizedBox(height: 4),
                            const Divider(),
                          ],
                        ),
                      ),
                      // Opção de logout
                      PopupMenuItem(
                        value: 'logout',
                        child: Row(
                          children: [
                            const Icon(Icons.logout, color: AppTheme.black),
                            const SizedBox(width: 8),
                            const Text('Sair'),
                          ],
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            // Conteúdo principal
            Expanded(
              child: !_periodSelected
                  ? const Center(child: CircularProgressIndicator())
                  : _isLoading
                      ? const Center(child: CircularProgressIndicator())
                      : Stack(
                          children: [
                            AnimatedContainer(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeInOut,
                              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 0),
                              child: LayoutBuilder(
                                builder: (context, constraints) {
                                  final screenWidth = constraints.maxWidth;
                                  final usePopupForTransactions =
                                      screenWidth < 1300;

                                  return ConstrainedBox(
                                    constraints:
                                        const BoxConstraints(maxWidth: 650),
                                    child: Row(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          // Calendário e Gráfico
                                          Expanded(
                                            flex: _showTransactions &&
                                                    !usePopupForTransactions
                                                ? 2
                                                : 1,
                                            child: Column(
                                              mainAxisSize: MainAxisSize.min,
                                              children: [
                                                // Calendário
                                                _isWeeklyView
                                                    ? SizedBox(
                                                        height: 400,
                                                        child: CalendarWidget(
                                                          key: _calendarKey,
                                                          startDate: _startDate,
                                                          endDate: _endDate,
                                                          transactions: _transactions,
                                                          onDayTap: _showDayDetails,
                                                          onViewChanged: (isWeekly) {
                                                            setState(() {
                                                              _isWeeklyView = isWeekly;
                                                            });
                                                          },
                                                        ),
                                                      )
                                                    : CalendarWidget(
                                                        key: _calendarKey,
                                                        startDate: _startDate,
                                                        endDate: _endDate,
                                                        transactions: _transactions,
                                                        onDayTap: _showDayDetails,
                                                        onViewChanged: (isWeekly) {
                                                          setState(() {
                                                            _isWeeklyView = isWeekly;
                                                          });
                                                        },
                                                      ),
                                                // Gráfico de progressão
                                                FutureBuilder<double>(
                                                  future: _calculateInitialBalance(),
                                                  builder: (context, snapshot) {
                                                    if (snapshot.connectionState == ConnectionState.waiting) {
                                                      return LayoutBuilder(
                                                        builder: (context, constraints) {
                                                          final screenHeight = MediaQuery.of(context).size.height;
                                                          final calculatedHeight = (screenHeight * 0.13).clamp(80.0, 200.0);
                                                          return SizedBox(
                                                            height: calculatedHeight,
                                                            child: const Center(
                                                              child: CircularProgressIndicator(),
                                                            ),
                                                          );
                                                        },
                                                      );
                                                    }
                                                    return BalanceChart(
                                                      startDate: _startDate,
                                                      endDate: _endDate,
                                                      dailyBalances: _calculateDailyBalancesForChart(),
                                                      initialBalance: snapshot.data ?? 0.0,
                                                    );
                                                  },
                                                ),
                                              ],
                                            ),
                                          ),
                                          // Lista de transações (só mostra ao lado se não for popup)
                                          if (_showTransactions &&
                                              !usePopupForTransactions) ...[
                                            const SizedBox(width: 12),
                                            Expanded(
                                              flex: 1,
                                              child: TransactionListWidget(
                                                transactions: _transactions,
                                                onTransactionUpdated: () async {
                                                  await _loadTransactions(
                                                      savePeriod: false);
                                                },
                                              ),
                                            ),
                                          ],
                                        ],
                                      ),
                                    );
                                },
                              ),
                            ),
                            // Botões flutuantes posicionados abaixo do calendário
                            Positioned(
                              bottom: 16,
                              right: 16,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  // Botão adicionar transação
                                  FloatingActionButton(
                                    onPressed: _showAddTransactionDialog,
                                    backgroundColor: AppTheme.black,
                                    child: const Icon(Icons.add,
                                        color: AppTheme.white),
                                  ),
                                  const SizedBox(width: 12),
                                  // Botão ver transações
                                  FloatingActionButton(
                                    onPressed: () {
                                      if (_showTransactions) {
                                        setState(() {
                                          _showTransactions = false;
                                        });
                                      } else {
                                        final screenWidth =
                                            MediaQuery.of(context).size.width;
                                        if (screenWidth < 1300) {
                                          _showTransactionsAsPopup();
                                        } else {
                                          setState(() {
                                            _showTransactions = true;
                                          });
                                        }
                                      }
                                    },
                                    backgroundColor: _showTransactions
                                        ? AppTheme.darkGray
                                        : AppTheme.black,
                                    child: Icon(
                                      _showTransactions
                                          ? Icons.receipt_long
                                          : Icons.receipt,
                                      color: AppTheme.white,
                                    ),
                                  ),
                                  const SizedBox(width: 12),
                                  // Botão toggle vista semanal/mensal
                                  FloatingActionButton(
                                    onPressed: () {
                                      _calendarKey.currentState?.toggleView();
                                      setState(() {
                                        _isWeeklyView = !_isWeeklyView;
                                      });
                                    },
                                    backgroundColor: AppTheme.black,
                                    child: const Icon(
                                      Icons.calendar_view_week,
                                      color: AppTheme.white,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
            ),

            // Resumo mensal
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
              decoration: const BoxDecoration(
                color: AppTheme.white,
              ),
              child: Row(
                children: [
                  // Saldo - à esquerda
                  Expanded(
                    child: _SummaryCard(
                      title: 'Saldo',
                      value: formatCurrency(
                          summary['gains']! - summary['expenses']!),
                      color: AppTheme.darkGray,
                      isFullWidth: true,
                      isTall: true,
                    ),
                  ),
                  const SizedBox(width: 16),
                  // Período e Histórico - à direita
                  Expanded(
                    child: Row(
                      children: [
                        Expanded(
                          child: InkWell(
                            onTap: _selectPeriod,
                            borderRadius: BorderRadius.circular(12),
                            child: Container(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 16,
                                vertical: 12,
                              ),
                              decoration: BoxDecoration(
                                color: AppTheme.white,
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(
                                  color: AppTheme.darkGray.withOpacity(0.2),
                                ),
                              ),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  // "Período" e ano juntos na mesma linha
                                  Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      Text(
                                        'Período',
                                        style: Theme.of(context)
                                            .textTheme
                                            .bodySmall
                                            ?.copyWith(
                                              color: AppTheme.darkGray,
                                            ),
                                      ),
                                      const SizedBox(width: 6),
                                      if (_startDate.year == _endDate.year)
                                        Container(
                                          padding: const EdgeInsets.symmetric(
                                            horizontal: 6,
                                            vertical: 2,
                                          ),
                                          decoration: BoxDecoration(
                                            color: AppTheme.darkGray.withOpacity(0.1),
                                            borderRadius: BorderRadius.circular(4),
                                          ),
                                          child: Text(
                                            '${_startDate.year}',
                                            style: Theme.of(context)
                                                .textTheme
                                                .bodySmall
                                                ?.copyWith(
                                                  fontSize: 10,
                                                  fontWeight: FontWeight.w600,
                                                  color: AppTheme.darkGray,
                                                ),
                                          ),
                                        )
                                      else
                                        Row(
                                          mainAxisSize: MainAxisSize.min,
                                          children: [
                                            Container(
                                              padding: const EdgeInsets.symmetric(
                                                horizontal: 6,
                                                vertical: 2,
                                              ),
                                              decoration: BoxDecoration(
                                                color: AppTheme.darkGray.withOpacity(0.1),
                                                borderRadius: BorderRadius.circular(4),
                                              ),
                                              child: Text(
                                                '${_startDate.year}',
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .bodySmall
                                                    ?.copyWith(
                                                      fontSize: 10,
                                                      fontWeight: FontWeight.w600,
                                                      color: AppTheme.darkGray,
                                                    ),
                                              ),
                                            ),
                                            Padding(
                                              padding: const EdgeInsets.symmetric(horizontal: 4),
                                              child: Text(
                                                '-',
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .bodySmall
                                                    ?.copyWith(
                                                      fontSize: 10,
                                                      fontWeight: FontWeight.w600,
                                                      color: AppTheme.darkGray,
                                                    ),
                                              ),
                                            ),
                                            Container(
                                              padding: const EdgeInsets.symmetric(
                                                horizontal: 6,
                                                vertical: 2,
                                              ),
                                              decoration: BoxDecoration(
                                                color: AppTheme.darkGray.withOpacity(0.1),
                                                borderRadius: BorderRadius.circular(4),
                                              ),
                                              child: Text(
                                                '${_endDate.year}',
                                                style: Theme.of(context)
                                                    .textTheme
                                                    .bodySmall
                                                    ?.copyWith(
                                                      fontSize: 10,
                                                      fontWeight: FontWeight.w600,
                                                      color: AppTheme.darkGray,
                                                    ),
                                              ),
                                            ),
                                          ],
                                        ),
                                    ],
                                  ),
                                  const SizedBox(height: 4),
                                  // Período formatado embaixo
                                  Text(
                                    _formatPeriodDates(_startDate, _endDate),
                                    style: Theme.of(context)
                                        .textTheme
                                        .bodyMedium
                                        ?.copyWith(
                                          fontWeight: FontWeight.w600,
                                          color: AppTheme.black,
                                        ),
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 8),
                        // Histórico
                        InkWell(
                          onTap: _showPeriodHistory,
                          borderRadius: BorderRadius.circular(12),
                          child: Container(
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(
                              color: AppTheme.black,
                              borderRadius: BorderRadius.circular(12),
                            ),
                            child: const Icon(Icons.history,
                                size: 30, color: AppTheme.white),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            // Ganhos e Despesas
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: const BoxDecoration(
                color: AppTheme.white,
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  Expanded(
                    child: _SummaryCard(
                      title: 'Ganhos',
                      value: formatCurrency(summary['gains']!),
                      color: AppTheme.incomeGreen,
                      count: _transactions
                          .where((t) => t.type == TransactionType.ganho)
                          .length,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _SummaryCard(
                      title: 'Despesas',
                      value: formatCurrency(summary['expenses']!),
                      color: AppTheme.expenseRed,
                      count: _transactions
                          .where((t) => t.type == TransactionType.despesa)
                          .length,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _SummaryCard extends StatelessWidget {
  final String title;
  final String value;
  final Color color;
  final int? count;
  final bool isFullWidth;
  final bool isTall;

  const _SummaryCard({
    required this.title,
    required this.value,
    required this.color,
    this.count,
    this.isFullWidth = false,
    this.isTall = false,
  });

  @override
  Widget build(BuildContext context) {
    final hasBorder = !isFullWidth && (title == 'Ganhos' || title == 'Despesas');
    
    return Container(
      padding: EdgeInsets.all(isTall ? 12 : 8),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: hasBorder
            ? Border.all(
                color: color.withOpacity(0.3),
                width: 1,
              )
            : null,
      ),
      child: isFullWidth
          ? Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                            color: AppTheme.darkGray,
                          ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      value,
                      style: Theme.of(context).textTheme.titleLarge?.copyWith(
                            fontWeight: FontWeight.w600,
                            color: color,
                            fontSize: isTall ? 18 : null,
                          ),
                    ),
                  ],
                ),
              ],
            )
          : Column(
              children: [
                Text(
                  title,
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        color: AppTheme.darkGray,
                      ),
                ),
                const SizedBox(height: 4),
                Text(
                  value,
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.w600,
                        color: color,
                      ),
                ),
                if (count != null) ...[
                  const SizedBox(height: 2),
                  Text(
                    '$count transações',
                    style: Theme.of(context).textTheme.bodySmall?.copyWith(
                          color: AppTheme.darkGray,
                        ),
                  ),
                ],
              ],
            ),
    );
  }
}
